In [102]:
# tensor
# 데이터를 저장하는 다차원 배열 구조
# 딥러닝이 학습할때 사용하는 자료구조
# 0차원 텐서 : 스칼라 - 단일 데이터
# 1차원 텐서 : 벡터 - 리스트 형태
# 2차원 텐서 : 행렬 - 행과 열로 이루어진 데이터, 흑백 이미지
# 3차원 텐서 : 큐브 - 컬러 이미지 흑백이미지 + 채널정보(R,G,B)
# 고차원 텐서 : 시퀀스 데이터, 비디오 데이터

# 데이터의 표준 형식 : 일관된 숫자 형식
# 효율적인 계산 : GPU 지원 병렬연산에 유리
# 딥러닝 프레임워크: TensorFlow, PyTorch 등에서 기본 데이터 구조로 사용

In [103]:
%pip install torch torchvision

Note: you may need to restart the kernel to use updated packages.


In [104]:
# 기본연산
import torch
# 빈 텐서 생성
x = torch.empty(3, 4)
x

tensor([[-3.4774e+00, -1.1794e+00,  7.5551e-01, -2.5559e-01],
        [ 1.8406e+00,  7.3831e-01,  1.5431e+00,  1.1731e+00],
        [ 5.9748e-04,  5.2099e-01,  3.1448e-01, -1.0541e+00]])

In [105]:
# 랜덤 텐서
x = torch.rand(3,4)
x

tensor([[0.6276, 0.8305, 0.7137, 0.1895],
        [0.1072, 0.2033, 0.2744, 0.2161],
        [0.7788, 0.1864, 0.0915, 0.5131]])

In [106]:
# 0으로 텐서 초기화
torch.zeros(3,4,dtype=torch.long)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [107]:
# 1로 채워진 텐서
torch.ones(3,4,dtype=torch.long)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [108]:
import numpy as np
print(np.array([3.4,3,2.1]))
print(torch.tensor([3.4,3,2.1]))

[3.4 3.  2.1]
tensor([3.4000, 3.0000, 2.1000])


In [109]:
# 기존의 텐서를 기반으로 새로운 텐서 생성
x = torch.ones(3,4)
torch.randn_like(x,dtype=torch.float)

tensor([[ 0.9343,  1.9118, -0.6265, -0.8302],
        [ 1.4155, -1.4551,  1.2930,  0.5699],
        [ 0.1685, -1.3304,  0.0252,  0.1851]])

In [110]:
import torch
x = torch.randn(3,4)
y = torch.randn(3,4)
x, y, x + y

(tensor([[ 0.0526,  0.7613,  0.3688,  0.8771],
         [-0.2065, -1.0811, -0.0823,  0.4372],
         [-0.3956,  0.5759,  0.4545,  0.7931]]),
 tensor([[-1.3685, -0.9103, -0.4250,  0.0986],
         [ 0.0697, -1.0005,  0.6676, -0.5758],
         [ 1.2123, -1.0376, -1.8571,  0.3889]]),
 tensor([[-1.3159, -0.1490, -0.0562,  0.9757],
         [-0.1368, -2.0817,  0.5854, -0.1386],
         [ 0.8167, -0.4617, -1.4026,  1.1820]]))

In [111]:
torch.add(x, y)  # x + y 와 동일

tensor([[-1.3159, -0.1490, -0.0562,  0.9757],
        [-0.1368, -2.0817,  0.5854, -0.1386],
        [ 0.8167, -0.4617, -1.4026,  1.1820]])

In [112]:
# in-place  y = y + x
y.add_(x)

tensor([[-1.3159, -0.1490, -0.0562,  0.9757],
        [-0.1368, -2.0817,  0.5854, -0.1386],
        [ 0.8167, -0.4617, -1.4026,  1.1820]])

In [113]:
# 행렬의 곱셈
x = torch.randn(3,4)
y = torch.randn(4,5)
x, y, torch.mm(x,y),x @ y  # 행렬곱셈 연산자

(tensor([[-1.4812,  1.2696, -0.0449, -0.7176],
         [ 0.8440, -1.0161, -0.1862,  0.9324],
         [-0.5334, -0.4080,  1.6332,  0.1483]]),
 tensor([[ 2.8669,  2.1186, -2.3762, -0.0225,  0.5160],
         [ 0.7957, -1.2561, -1.6385, -1.2361,  0.3514],
         [ 1.4838,  0.6663,  0.8660,  0.1513, -0.3726],
         [-1.3166, -0.5622, -0.3370,  0.1487,  0.4543]]),
 tensor([[-2.3582, -4.3593,  1.6425, -1.6495, -0.6275],
         [ 0.1074,  2.4162, -0.8163,  1.3475,  0.5715],
         [ 0.3742,  0.3873,  3.3002,  0.7856, -0.9597]]),
 tensor([[-2.3582, -4.3593,  1.6425, -1.6495, -0.6275],
         [ 0.1074,  2.4162, -0.8163,  1.3475,  0.5715],
         [ 0.3742,  0.3873,  3.3002,  0.7856, -0.9597]]))

In [114]:
# 슬라이싱 가능
x = torch.randn(4,5)
x[1,1], x[1,1].item(), type(x[1,1]),type(x[1,1].item())

(tensor(0.0705), 0.07051914930343628, torch.Tensor, float)

In [115]:
# x 4 by 4
# view : reshape -> 텐서 모양 변경
# size : shape -> 텐서 모양 확인
# 가독성... view size 사용되었다는 것은 해당 자료구조가 텐서라는것을 명시
# x.view(-1,8) , x.size()

In [116]:
# 텐서 -> 넘파티
import numpy as np
import torch
a = torch.ones(5)
a.numpy()

array([1., 1., 1., 1., 1.], dtype=float32)

In [117]:
# 넘파이 -> 텐서
b = np.array([1,2,3,4,5])
torch.from_numpy(b)

tensor([1, 2, 3, 4, 5])

In [118]:
# GPU 사용
if torch.cuda.is_available():
    device = torch.device('cuda') # GPU 장치 객체 생성
    # 텐서들은 GPU에서 연산해야되기 때문에 생성을 GPU에서 생성
    x = torch.ones(5, device=device) # GPU에 텐서 생성
    y = torch.ones(5) # CPU에 텐서 생성
    y = y.to(device)  # y 텐서를 GPU로 이동
    z = x + y
    print(f"GPU 연산 결과: {z}")
    print(f"다시 CPU로 이동: {z.to('cpu', torch.double)}")
else :
    print("GPU 사용 불가")
    device = torch.device('cpu')


GPU 사용 불가


In [119]:
# 행렬 곱
# (x, y) * (x1, y1)
# y, x1의 차수는 같아야한다...
# 행렬곱의 결과는 x, y1

# 텐서는 딥러닝을 위해 만들 자료구조... 내부에 gpu 연산에 특화된 구조 일반적인 모양은 넘파이와 동일
# 텐서는 gpu 연산을 지원

In [120]:
# 자동 미분(AutoGrad) 매 계산과정마다 해당 계산과정의 미분값을 저장
# 파이토치 requires_grad 속성을 True로 설정하면 계산 그래프라는 형태로 기록 - 동영상 녹화와 비슷한 원리
# .backward() 호출하면 이 과정을 거꾸로 되갑으면서 각 단계의 미분값을 계산해 최종 기울기를 얻는다


In [121]:
x = torch.ones(2,2, requires_grad=True)
x, x.size()

(tensor([[1., 1.],
         [1., 1.]], requires_grad=True),
 torch.Size([2, 2]))

In [122]:
y = x + 2  # y도 계산그래프에 추가
print(y, y.grad_fn)
z= y * y * 3
out = z.mean()
z, out

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>) <AddBackward0 object at 0x000001B2E60092D0>


(tensor([[27., 27.],
         [27., 27.]], grad_fn=<MulBackward0>),
 tensor(27., grad_fn=<MeanBackward0>))

In [123]:
# 기울기....구하는 과정을.... 역전파 --> 기울기 계산
# 최종결과가 out에서 부터 시작해서 계산그래프를 거꾸로 ㄱ거슬러 올라가면서 미분의 연쇄법칙을사용해서 미분값을  계산
# out을 x에 대해서 미분
out.backward()  # out에 대한 역전파 계산
x.grad  # x에 대한 기울기 출력

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

In [124]:
# out = 1/4(z1+z2+z3+z4)
# z = 3y^2
# y = x + 2

# d-out/dxi = 3*(xi +2)/4 * 2 = 3/2 *(xi +2)

In [128]:
# 기울기 제어
# 역전파, torch.no_grad, detach
# required_grad = True 연산 추적
import torch
x = torch.randn(3, requires_grad=True)
print(x)
# y 는 x로부터 연산기록을 물려받음
y = x * 2
# 노름(유클리드 노름)  벡터의 크기를 측정하는 방법(원점으로부터 벡터까지의 거리)  모든 요소를각각 제곱하고 모두 더해서 결과에 제곱근(루트)
# y의 실제데이터의 크기를 확인해서 반복
i = 0
while y.data.norm()  < 1000:
    y = y*2
    i += 1
print(f'y: {y}')    
print(f'반복횟수 : {i}   y = x*2^i+1')  

# 벡터에 대한 역전파(야코비안 행렬)
# 벡터를 벡터로 미분하면 결과는 행렬인 야코비안 행렬
# pytorch는 전체 야코비안 행렬을  직접 계산하는 대신 야코비안 - 벡터 곱을 계산해서 메모리를 절약
v = torch.tensor([0.1,1.0,0.0001], dtype=torch.float)
y.backward(v)  # y를 x에 대해 미분한 야코비안 행렬과 입력으로 제공된 벡터v를 곱하라는 의미
# Vt *
print(f'x.grad: {x.grad}')

tensor([-0.3330, -1.4026,  0.4785], requires_grad=True)
y: tensor([ -340.9592, -1436.2125,   489.9508], grad_fn=<MulBackward0>)
반복횟수 : 9   y = x*2^i+1
x.grad: tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


```
스칼라 백워드 Scalar Backward : 역전파로 구하는 기울기가 하나일때
out.backward()
최종점수가 숫자하나  ex) 수학공부 1시간 했을때 최종점수에 몇점의 영향을 줬는지
최종 목표가 하나(스칼라) 이기때문에 각 원인(각 변수)의 기여도를 바로 계산

벡터 백워드 Vector Backward : 기울기가 여러개일때
y.backward(v)
과목별 점수가 담긴 성적표(벡터) 공부시간이 성적에 얼마나 영향을 줬는지 물어보면 애매함 국어성적? 영어성적?
가중치 또는 중요도를 알려주는 벡터 v = torch.tensor([0.1,1.0,0.0001], dtype=torch.float)
중요도를 반영해서 최종적으로 공부시간의 기여도를 확인
```

In [132]:
# 각 학습을 진행하면서도중에 모델의 성능을 평가가 필요 - 기울기 계산을 하면 안됨
with torch.no_grad():
    print(f'no_grad 내부 : {(x**2).requires_grad}')

# .detach() 계산그래프에서 텐서를 분리
print(f'detach 전 {y.requires_grad}')
y = x.detach()
print(f'detach 후 {y.requires_grad}')

no_grad 내부 : False
detach 전 False
detach 후 False
